jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshTemplate.java, jbehave-support-core/src/main/resources/get-log-between-timestamps-template.awk, jbehave-support-core/src/main/resources/get-log-between-timestamps.awk, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
Take into consideration logs where each log line doesn't start with timestamp
https://github.com/EmbedITCZ/jbehave-support/issues/8
=> Improve the way how log part between timestamps is retrieved using awk

jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/WsXmlReporterExtension.java
=> Fixed potential NPE in ws reporter if soap header is not present.

jbehave-support-core/src/main/resources/functions.js, jbehave-support-core/src/main/resources/report.xslt
Resolves #34, example screenshots below.
SSH:
REST:
SOAP:
=> Added copy to clipboard button to SOAP/REST/SSH in xml report

jbehave-support-core/pom.xml, jbehave-support-core/src/main/resources/functions.js, jbehave-support-core/src/main/resources/index.xslt, jbehave-support-core/src/main/resources/report.xslt
=> JBUS version should now appear in reports again

jbehave-support-core/pom.xml, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/ExpressionEvaluatorImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/UnescapeCommand.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/report/XmlReporterFactory.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/AbstractXmlReporterExtension.java, pom.xml
Introduced commons-text as a replacement for commons-lang3 deprecated APIs
=> Introduced commons-text dependency

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/ExpressionEvaluatorImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/TestContextCopyCommand.java
=> Commands should now receive unescaped parameters

jbehave-support-core/docs/General.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/CommandHelper.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/support/TestContextUtil.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/CommandHelperTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/ExpressionEvaluatorTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/EscapingInContext.story
=> Added the option to escape ' character

jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/RestXmlReporterExtension.java, jbehave-support-core/src/main/resources/report.xslt
=> Added support for multipart/form-data mimetype in rest xml reporter

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/sql/InterceptingNamedParameterJdbcTemplate.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/sql/SqlStatementContext.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/SqlXmlReporterExtension.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java, jbehave-support-core/src/main/resources/functions.js, jbehave-support-core/src/main/resources/report.xslt, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
=> Introduced SQL reporting extension

jbehave-support-core/docs/Web-testing.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/YamlElementLocatorParser.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/by/ByFactoryResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/by/CssByFactory.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/by/XpathByFactory.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/ByFactory.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/ByFactoryResolver.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/ByFactoryResolverTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/YamlElementLocatorParserTest.groovy
=> Added option to use custom 'By' types in yaml ui mappings

jbehave-support-core/src/main/java/org/jbehavesupport/core/support/RequestFactory.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/RequestFactoryTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy
=> [FIX #96] User defined type is resolved as first while creating WS request

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverDelegatingInterceptor.java
Fixed issue with webdriver getScreenshotAs detection - can have multiple return parameter types
=> Fixed issue with webdriver getScreenshotAs detection

jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Sql.story
Closes #84 
Fixed potential issue with sql result validation changing the original result data.
=> Fixed potential issue with sql result validation

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/sql/InterceptingNamedParameterJdbcTemplate.java
=> Fixed NPE when SQL Reporter is not present.

jbehave-support-core/docs/Web-service.md
=> Updated MD with soap fault checking example.

jbehave-support-core/src/main/java/org/jbehavesupport/core/JBehaveDefaultConfig.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/TestContextImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/ExpressionEvaluatorImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/VerifierResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebElementLocatorImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebElementRegistryImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/action/WebActionBuilderImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/action/WebActionResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/by/ByFactoryResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/property/WebPropertyResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/waitcondition/WebWaitConditionResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverFactoryResolverImpl.java
=> Default internal component implementations are now conditional

pom.xml
Fix for https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-174736
=> Updated jackson to latest version

jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebWaitCondition.story
=> Added expression support for web wait condition.

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/util/ArrayComparator.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/EqualsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/NotEqualsVerifier.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/EqualsVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/NotEqualsVerifierTest.groovy
=> Added array support for Equals and NotEquals verifiers

.travis.yml, ci/build.sh, ci/system-test.sh, ci/test.sh, ci/trusty-before-system-test.sh, jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/jbehave-support-core-test-oxm/pom.xml, jbehave-support-core-test/pom.xml, jbehave-support-core/pom.xml, pom.xml
Solves #106 
Added openjdk11 to travis
=> Java 11 compatibility fixes

.travis.yml, ci/report_upload.sh
Working version - the comment below is automated response made through API
=> Report uploading

jbehave-support-core/src/main/java/org/jbehavesupport/core/support/RequestFactory.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebService.story
Fixes #101
Original commit + rename commit from me
=> [FIX #101] Instantiating inlaid JAXB elements in request factory

jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/SecurityConfig.java, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/action-test.html, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/frames.html, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/iframes/first-frame.html, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/iframes/second-frame.html, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/iframes/third-frame.html, jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/title.html, jbehave-support-core/docs/Web-testing.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/action/ForceClickWebAction.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebAction.story, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebNavigation.story, jbehave-support-core/src/test/resources/ui-mapping/ui-mapping.yaml
FORCE_CLICK web action.
Documentation for web steps amended.
=> New web steps for tabs and frames.

.travis.yml, ci/trusty-before-system-test.sh
Simplified ci to use only xenial (and changed to openjdk8 instead of oraclejdk8)
=> Simplified ci to use only xenial

jbehave-support-core-test/jbehave-support-core-test-app-domain/src/main/java/org/jbehavesupport/core/test/app/domain/Mirror.java, jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/UserController.java, jbehave-support-core/docs/Rest-api.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/ExamplesTableUtil.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/issue/NegativeRestHandling.story, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/issue/NegativeRestScenariosIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Rest.story, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
=> [FEATURE #92] Success handlers for REST steps

jbehave-support-core/docs/General.md, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Sql.story, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebService.story, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebServiceFail.story
Added link to expression commands
Fixed typos: Scenarious -> scenarios
=> Minor fixes

jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/CurrentDateTimeCommandTest.groovy
=> Fixed imperfect comparison

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/ContainsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/EqualsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/GreaterThanVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/LowerThanVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/NotContainsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/NotEqualsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/NotNullVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/RegexFindVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/RegexVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/SizeEqualsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/SizeGreaterThanVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/SizeLowerThanVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/VerifierResolverImpl.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerificationSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerifierNames.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerifierResolver.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ws/WebServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/verification/VerifierResolverTest.groovy
Verifier resolver can return default verifier, if given verifier is null.
Fixed #135
=> Improved verifier resolver

ci/report_upload.sh
Needed for #148 to correctly zip and upload report folder (support for folders will also need to be added for JRS).
=> Added support for directories in report uploading script.

jbehave-support-core/docs/Web-testing.md
Info about timeouts is already written on line 33
=> Removed old TODO

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/FileNameResolver.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebScreenshotCreator.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/RestXmlReporterExtension.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
=> Generalized method for naming supporting files for reporting

jbehave-support-core-test/jbehave-support-core-test-oxm/src/main/resources/name.xsd, jbehave-support-core/src/main/java/org/jbehavesupport/core/ws/WebServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/WebServiceTestIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebService.story
Nested lists can be now written both with brackets and periods.
Ex. both address[0].city and address.0.city are possible
Part of: #91
=> Web service supports both period and bracket notations

jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerificationSteps.java
- According to new experiences check od mandatory columns was added to step
=> Verification steps check added

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebScreenshotCreator.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverDelegatingInterceptor.java
Fixed issue of taking fail screenshots even if no web browser is open - it doesn't do that any more
=> Fixed taking fail screenshots of nothing

jbehave-support-core/src/main/resources/report-generator/envelope.xslt
Addresses issue discovered during the revision process for #168 (should be merged before)
=> Fixed switching between reports

jbehave-support-core/src/main/resources/report.xslt
=> Fixed broken collapsing

jbehave-support-core/src/main/resources/report.xslt
=> Fixed broken reports in IE and MS Edge

jbehave-support-core/src/main/resources/report.xslt
=> Fixed opening and collapsing of step details in reports

CONTRIBUTING.md, README.md, docs/IntegrationTest.md, jbehave-support-core/README.md
Moved all info for developers from the main README.md to CONTRIBUTING.md.
Added simple setup guide for users to main README.md
Added more info to contributors guide
=> Improved documentation

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/FileNameResolver.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/BytesCommandTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/ScreenshotTestIT.groovy
\+ Fixed a bug in FileNameResolver
=> Added groovy tests for BytesCommand and creating screenshots

jbehave-support-core/docs/Ssh.md, jbehave-support-core/pom.xml, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ssh/SshStepsTimestampCacheMockIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Ssh.story, pom.xml
- reading of logs is now using start and end timestamp
- reading of logs is now using cache
=> Update Ssh steps

pom.xml
=> Updated jackson versions to fix snyk security issues.

jbehave-support-core-test/jbehave-support-core-test-oxm/src/main/resources/name.xsd, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/converters/ConversionServiceProcessor.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/converters/StringToXmlEnumConverterFactory.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebService.story
Closes #197 
Feel free to suggest different xml structure 🙂
=> #197 - WebServiceSteps should now correctly support xsd enum values

jbehave-support-core/docs/Ssh.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/JBehaveDefaultConfig.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshHandler.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Ssh.story
=> SshHandler introduced

jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/issue/DifferentDatabaseResultErrorMessage.groovy
Changed the error message for SQL comparison to be deterministic and use ordered keyset.
Should also fix the currently failing #239 pipeline on Java 11.
=> Changed the error message for SQL comparison to be deterministic

.travis.yml, CONTRIBUTING.md, ci/browserstack.sh, ci/system-test.sh, jbehave-support-core/pom.xml, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/issue/BrowserStackIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java, jbehave-support-core/src/test/resources/test.yml, pom.xml
=> Browserstack testing setup

.github/workflows/browserstack.yml, .github/workflows/ci.yml
Complete pipeline rewrite to github actions workflows. Does not upload reports anywhere but exports them as artifact.
=> Github actions pipeline setup

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/ExampleTableConstraints.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/FirefoxWebDriverFactory.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshHandler.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebTableSteps.java
=> Deprecation documentation improvements.

jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java
Updated:
Then these rows are present in the query result:
To use equals verifier.
=> SQLsteps update

.github/workflows/ci.yml, README.md
I still left it in Travis pipeline, so ideally merge after #287 
Related to #56
=> Removed Codacy from pipeline.

jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/pom.xml, jbehave-support-core/pom.xml, pom.xml
=> Replaced javax activation and annotation by jakarta ones.

.github/workflows/browserstack.yml, .github/workflows/ci.yml
=> Changed browserstack and sonar pipeline to run only on EIT repo.

jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/pom.xml, jbehave-support-core/pom.xml
Last commit - the migration should now be complete
=> Replaced javax mail and interceptor by jakarta ones.

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/SkipSslVerificationHttpRequestFactory.java
=> Changed default hostnameVerifier for rest steps to noop.

jbehave-support-core/src/main/resources/report-generator/story.xslt, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/SshReport.story
Added formatting for multi-line values in test context.
=> Format test context in reports

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/ExamplesTableUtil.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceSteps.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/ws/WebServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/ExamplesTableUtilTest.groovy, pom.xml
=> Check for duplicates in examples table added

jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/static/action-test.html, jbehave-support-core/docs/Web-testing.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/action/ScrollOnWebAction.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/property/DefaultWebProperties.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/WebScrollAction.story
- Sometimes we have to focus element, for example:
- Before clicking on it
- Before taking screenshot
=> Focus web action

README.md, jbehave-support-core/README.md, jbehave-support-core/docs/Best-practices.md, jbehave-support-core/docs/Health-checks.md
Feel free to add another best practices if you think of something 🙂
=> Added "best practices" section to markdown docs.

jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java
=> Last bug solved

README.md, jbehave-support-core/README.md, jbehave-support-core/docs/Known-issues.md
Closes #331 
Feel free to add more if you remember some.
=> Added known issues section to markdown docs.

jbehave-support-core/docs/Web-testing.md
=> Added custom web action documentation + minor doc improvements.

jbehave-support-core/src/test/groovy/org/jbehavesupport/core/report/XmlReportIT.groovy
And maybe hopefully solved #349, #350 and #351 🤞
=> Improved XmlReportIT.

jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/SqlXmlReporterExtension.java
=> Fixed potential NPE from sql reporter extension

README.md
The old selector doesn't work anymore, I updated it in order for the scenario to work on the current version of the google search result page.
=> Updated search.output.css selector in Google story

jbehave-support-core/docs/Rest-api.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/rest/RestIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Rest.story
=> Added option to save and verify raw json body in rest steps.

jbehave-support-core/pom.xml, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/rest/RestIT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ssh/SshSettingTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/WebServiceTestIT.groovy, pom.xml
Should fix lots of tests currently not running in the CI pipeline at all.
=> Added junit vintage dependency due to Spock using junit 5 internally.

.github/workflows/browserstack.yml, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/action/DoubleClickWebAction.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverUtil.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackSafariT.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
Based on #475, please review merge after it and review just the commit 779100c92ad60c8f0f8cb3c9a6d52b2dba182c96.
=>  Fixed double clicking in Safari.

jbehave-support-core/docs/Deprecated.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/support/YamlPropertiesConfigurer.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/support/YamlPropertySourceFactory.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
Open points: 
- package and naming for the new class
- deprecation warning
- do we want to deprecate or do we want to keep both ways and just mention that one is not suitable for config (and just test data and similar stuff)
=> Rewritten yaml properties loading.

jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/pom.xml, jbehave-support-core/pom.xml, pom.xml
Not needed on our side anymore - it is brought transitively where needed (jaxb + soap mainly).
=> Removed jakarta activation dependency.

jbehave-support-core/docs/Expression-commands.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/EnvCommand.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/EnvCommandTest.groovy
Closes #414 
Open points:
- do we want the name to be ENV?
- do we want to handle case sensitivity, different cases like boot does?
- do we want to allow null return or throw exception?
=> Introduced new Env command.

jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/rest/RestIT.groovy
=> Fixed saving of rest headers from response if body is empty.

jbehave-support-core/docs/Rest-api.md, jbehave-support-core/docs/Web-service.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestLoggingInterceptor.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/test/resources/logback.xml
Logging example:
18:53:09.709 [pool-1-thread-1] TRACE o.j.core.rest.RestLoggingInterceptor - Request body:  with headers: [Accept:"text/plain, application/json, application/*+json, */*", x-cuid:"1", Content-Type:"application/json", Content-Length:"0"]
18:53:09.823 [pool-1-thread-1] TRACE o.j.core.rest.RestLoggingInterceptor - Response body: [{"id":225,"firstName":"first name 1","lastName":"last name 1","addresses":[{"city":"city 0 0","country":"country 0 0","details":null},{"city":"city 0 1","country":"country 0 1","details":null}],"picture":null},{"id":5,"firstName":"Emanuel","lastName":"Rego","addresses":null,"picture":null},{"id":9,"firstName":"Alison","lastName":"Cerutti","addresses":null,"picture":null},{"id":10,"firstName":"Bruno","lastName":"vFAJymIreI","addresses":[],"picture":null …
=> RestLoggingInterceptor

jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/rest/NegativeRestScenariosIT.groovy
Solves #469
@xsmrcek please check if this is what you intended or not 🙂
=> Added support for multiple rest assertions

jbehave-support-core/docs/General.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/GreaterThanOrEqualVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/LowerThanOrEqualVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/SizeGreaterThanOrEqualVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/SizeLowerThanOrEqualVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerifierNames.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/GreaterThanOrEqualVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/LowerThanOrEqualVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/SizeGreaterThanOrEqualVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/SizeLowerThanOrEqualVerifierTest.groovy
=> Added verifiers for "lower or equal" + "great or equal".

jbehave-support-core/src/main/resources/report-generator/story.xslt
=> Fixed report escaping problem in step values.

jbehave-support-core/src/main/resources/report-generator/restXmlReport.xslt
=> Added headers to xslt from RestReportExtension

jbehave-support-core/src/main/java/org/jbehavesupport/core/AbstractSpringStories.java, pom.xml
=> JBehave upgrade

jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/RestXmlReporterExtension.java
=> Fixed potential NPEs in rest reporter for failed rest response

.github/workflows/ci.yml, CONTRIBUTING.md, docs/IntegrationTest.md, jbehave-support-core-test/README.md, jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core/pom.xml, pom.xml
Removed jetty maven plugin along with development and integration-test maven profiles.
=> Removed jetty maven plugin + maven profiles

jbehave-support-core/docs/General.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/MathEqualsVerifier.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerifierNames.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/EqualsVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/MathEqualsVerifierTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Verification.story
Added a new MATH_EQ verifier which attempts to convert the values to a double, then compares them.
Related to issue #661
=> Mathematical eqality verifier (issue #661)

.github/workflows/browserstack.yml, .github/workflows/ci.yml, CONTRIBUTING.md, README.md, jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/jbehave-support-core-test-oxm/pom.xml, pom.xml
=> Changed codebase to java 17.

jbehave-support-core-test/jbehave-support-core-test-app-domain/pom.xml, jbehave-support-core-test/jbehave-support-core-test-app/pom.xml, jbehave-support-core-test/jbehave-support-core-test-oxm/pom.xml, jbehave-support-core-test/pom.xml, jbehave-support-core/pom.xml, pom.xml
This reverts commit 461dfd41961f3aeb27639ea676afdd72f9aa90b9.
=> Revert "[maven-release-plugin] prepare release jbehave-support-1.4.0"

.github/workflows/ci.yml, README.md, jbehave-support-core/src/main/java/org/jbehavesupport/core/AbstractSpringStories.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/FullScenarioNameStorer.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/BigDecimalConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/ExamplesEvaluationTableConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/LocalDateConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/LocalDateTimeConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/NullStringConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/XMLGregorianCalendarConverter.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/parsers/FilteringStoryParser.java, jbehave-support-core/src/main/java/org/jbehavesupport/core/report/XmlReporter.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/FullScenarioNameStorerTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/parameterconverters/BigDecimalConverterTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/parameterconverters/LocalDateConverterTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/parameterconverters/LocalDateTimeConverterTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/parameterconverters/NullStringConverterTest.groovy, jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/parameterconverters/XMLGregorianCalendarConverterTest.groovy, pom.xml
(Also solves the issue with reflection on String causing us to use add-opens previously)
=> Upgrade to JBehave 5.

jbehave-support-core/docs/Deprecated.md, jbehave-support-core/docs/Web-testing.md, jbehave-support-core/pom.xml, jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/ChromeWebDriverFactory.java, pom.xml
=> Upgrade selenium to latest version

jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestLoggingInterceptor.java
=> Improve RestLoggingInterceptor

jbehave-support-core/src/test/groovy/org/jbehavesupport/test/TestConfig.java, jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestSupportBrowserStack.groovy, jbehave-support-core/src/test/resources/test.yml
It wont be green, but at least it will be starting and run the tests in browserstack... Next phase - go browser by browser, check logs/videos etc and fix each test to pass.
=> Use new browserstack setup for Selenium 4.

jbehave-support-core/docs/General.md
=> Fixed wrong link to escaping story in docs.

jbehave-support-core/docs/Deprecated.md, jbehave-support-core/docs/Migration.md
=> Update migration guide.
