jbehave-support-core-test/jbehave-support-core-test-app/pom.xml
jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/JbehaveSupportCoreTestApplication.java
jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/SshConfig.java
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/application.yml
jbehave-support-core-test/pom.xml
jbehave-support-core/pom.xml
pom.xml

spring-boot-starter-remote-shell was removed, so I pulled necessary bits to SshConfig
It also fixes security alert whereby Boot pulls jackson dependencies with version 2.9.7

Upgrade to Spring Boot 2.0.6.RELEASE

---

jbehave-support-core/src/main/java/org/jbehavesupport/core/jms/JmsSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/ws/WebServiceSteps.java

Resolves #32 - messages are now aligned to HealthCheckSteps example,

Aligned error messages when searching for qualified beans.

---

pom.xml

General question related to further dependency updates - do we want to move to Spring 5 or stay on 4? (Could potentially fix the new vulnerability reported by snyk on this PR)

Updated spring-ws + webdriver manager after snyk vulnerability report

---

jbehave-support-core/docs/Expression-commands.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/RandomGeneratorHelper.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/CurrentDateCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/CurrentDateTimeCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/DateParseCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/DateTimeParseCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/FormatDateCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/FormatDateTimeCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/NextCalendarDayCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/NextMonthCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/RandomDateCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/expression/temporal/RandomDateTimeCommand.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/LocalDateTimeConverter.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/EmptyStringCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/CurrentDateCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/CurrentDateTimeCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/DateParseCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/DateTimeParseCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/FormatDateCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/FormatDateTimeCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/NextCalendarDayCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/NextMonthCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/RandomDateCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/RandomDateTimeCommandTest.groovy

Solves #28 
Open points - NextMonth and NextCalendarDay commands - do we want datetime alternatives?
Do we want to add shortcodes for datetime parse and format date time similar to date versions? E.g.
``` 
shorthands.put("DP", "DATE_PARSE");
shorthands.put("FD", "FORMAT_DATE");
```

Added commands for dateTime support

---

jbehave-support-core/docs/Expression-commands.md

Fixed typo for NEXT_CALENDAR_DAY command in documentation.

---

jbehave-support-core/docs/Reporting.md

Updated reporting markdown with info about SQL extension, plus info that at least one extension has to be registered.

Updated reporting markdown doc

---

jbehave-support-core-test/jbehave-support-core-test-app/pom.xml
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/META-INF/services/javax.xml.bind.JAXBContext
jbehave-support-core-test/jbehave-support-core-test-oxm/src/main/resources/META-INF.services/javax.xml.bind.JAXBContext
jbehave-support-core-test/pom.xml
jbehave-support-core/pom.xml
jbehave-support-core/src/test/resources/META-INF/services/javax.xml.bind.JAXBContext
pom.xml

Moxy supports converters for java8 data types which were working before explicitly adding glassfish jaxb runtime.
I have not added test for it since it would include changing xjb, creating new LocalDate converter, changing test story, changing test ws and potentially changing test xsd (but if someone feels strongly about it I can do it, it just did not seem worth the hassle to me).

Changed Jaxb implementation to moxy

---

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebElementRegistryImpl.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/YamlElementLocatorParser.java

Today we faced issue where tester made duplicate mapping for page and system taken one of the mappings without throwing any error.
I tested behaviour manually by adding file with duplicate mapping.

Duplicate ui mapping now throws IllegalStateException

---

jbehave-support-core/docs/General.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/ExampleTableConstraints.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/RegexFindVerifier.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/VerifierNames.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/verification/VerificationSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/RegexFindVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/SampleStoriesIT.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Verification.story

REGEX_FIND verifier is best used for in log checks. Like 
| myAppRequest.*?{CP:INDENTIFIER}.*?testedValue>{CP:TESTED_VALUE}<.*?myAppRequest | REGEX_FIND|.
Steps for columns comparing is good for comparing SQL resutls with many columns, because writing 100 columns on one line is really ugly., so it;s better to save all values from both selects to context and compare them in another step. Of course it have mutch more examples of usage.

RegexFindVerifier and Comparing of columns

---

jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/DatabaseConfig.java
jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/NameEndpoint.java
jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/SshConfig.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/file/FileSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/healthcheck/HealthCheckSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/FullScenarioNameStorer.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/ExamplesEvaluationTableConverter.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/parameterconverters/ExpressionEvaluatingParameterConverters.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/GreaterThanVerifier.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/verification/LowerThanVerifier.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebElementRegistryPopulator.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/EnvironmentInfoXmlReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/FailScreenshotsReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/RestXmlReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/ServerLogXmlReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/TestContextXmlReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/sql/SqlSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/ws/WebServiceSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestContextSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestWebServiceHandler.java

I left @Autowired on:
* optional dependencies
* groovy files
* abstract classes / classes where inheritance is expected - so requiredargs ctor can be used there without any hassle

Switched to constructor injection

---

README.md
jbehave-support-core/docs/Web-testing.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/JBehaveDefaultConfig.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverDelegatingInterceptor.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/webdriver/WebDriverFactoryResolverImpl.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebDriverFactoryResolver.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java

+ added link to official Jbehave site to README.md

Users can now change browsers mid-story

---

.editorconfig

IDEA's "optimise imports" function doesn't want to squash imports under asterisks anymore.

No more asterisk imports

---

jbehave-support-core/src/main/resources/index.xslt
jbehave-support-core/src/main/resources/report.xslt

Fixed switching between reports and removed the text "!DOCTYPE html" in top left corner in Firefox
Fixes #177

Fixed Firefox

---

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebScreenshotCreator.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/FailScreenshotsReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/ScreenshotReporterExtension.java

The path to a screenshot is now written to the xml, not just the file name.

Loading screenshots from custom directory to xml reports

---

jbehave-support-core/docs/Reporting.md
jbehave-support-core/docs/Web-testing.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebScreenshotCreator.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/web/WebScreenshotListener.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/ScreenshotReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebScreenshotEvent.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebScreenshotType.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/ScreenshotTestIT.groovy

Event listener and event added
Moved enum Type to separate class outside of internal
MD for screenshots and screenshot extension added
I creted two versions of listener and kept one as a comment
The one using hierarchy is way better readable
The one using Map with runnable is redundant solution but I personaly like it more, becase it create screenshots named after chosen mode.

Event listener for screenshot

---

jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshSteps.java

With PR #161 we accidentally renamed existing step. So this is to mai…ntain backwards compatibility of releases.

Backwards compability fix

---

jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/ExamplesTableUtil.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/web/WebSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/issue/ExamplesTableUtilTest.groovy

Added asserts to web steps mandatory columns

---

jbehave-support-core/docs/Reporting.md
jbehave-support-core/src/main/resources/report-generator/envelope.xslt
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/SshReport.story

Formated narrative better in reports and added doc about it.

Format narrative in reports

---

jbehave-support-core/docs/Rest-api.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Rest.story

Added the possibility to send an empty json list in rest steps and fixed 3 SonarLint warnings.
Solves https://github.com/EmbedITCZ/jbehave-support/issues/326

Added the possibility to send an empty json list in rest steps

---

jbehave-support-core/README.md
jbehave-support-core/docs/Deprecated.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshTemplate.java

Added info about deprecated steps to MDs.

Deprecated doc added

---

jbehave-support-core/docs/Web-service.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/support/RequestFactory.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/WebServiceTestIT.groovy

Resolves #100 
One of the possible solutions - alternative could be to use different command than NULL, but IMO not setting in examples table=not sent, setting explicitly to null=empty node sounds reasonable from end users perspective... But feel free to suggest another solution if this does not work for you.

Added option to send empty node in WS steps.

---

jbehave-support-core-test/README.md
jbehave-support-core-test/jbehave-support-core-test-app/src/main/java/org/jbehavesupport/core/test/app/SplunkController.java
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/application.yml
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/splunk/login-response.xml
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/splunk/search-data-response.json
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/splunk/search-no-data-response.json
jbehave-support-core-test/jbehave-support-core-test-app/src/main/resources/splunk/server-info-response.xml
jbehave-support-core/README.md
jbehave-support-core/docs/Splunk.md
jbehave-support-core/pom.xml
jbehave-support-core/src/main/java/org/jbehavesupport/core/JBehaveDefaultConfig.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/splunk/SplunkArgNames.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/splunk/SplunkEventFields.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/splunk/SplunkOutputModes.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/OneShotSearchSplunkClient.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/SplunkClient.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/SplunkConfig.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/SplunkSearchResultEntry.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/SplunkSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/TestConfig.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/SampleStoriesIT.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Splunk.story
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
jbehave-support-core/src/test/resources/test.yml
pom.xml

The changes relate to Splunk custom steps. The intention is to let dev teams to assert some of the events also in Splunk logs.
Please note that the test runs against mocked Splunk instance and the development was conducted with locally running Splunk Docker image.
There have been some talks with EIT Splunk Monitoring team to let us to use java sdk, but it may take a while until we are capable to use it in EIT domain.

Splunk Custom Steps

---

.github/workflows/browserstack.yml
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackSafariT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java

BROWSERSTACK_KEY will need to be updated to new one manully in github settings once merged.

Browserstack improvements

---

.github/workflows/browserstack.yml
CONTRIBUTING.md
jbehave-support-core/pom.xml
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackChromeT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackFirefoxT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackSafariT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestSupportBrowserStack.groovy
pom.xml

Rewritten BrowserStack tests to expect Local binary already running in the background.
Should significantly stabilize our BrowserStack pipeline. Con: developer is expected to download and run the local binary on his computer when running the BrowserStack tests.

BrowserStack Local rewrite

---

jbehave-support-core/docs/Reporting.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/internal/splunk/SplunkSearchContext.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/report/extension/SplunkXmlReporterExtension.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/splunk/OneShotSearchSplunkClient.java
jbehave-support-core/src/main/resources/functions.js
jbehave-support-core/src/main/resources/report-generator/envelope.xslt
jbehave-support-core/src/main/resources/report-generator/splunkXmlReport.xslt
jbehave-support-core/src/main/resources/report.xslt
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestConfig.java

New extensions for splunk.
How does it look?
There is more attributes in splunk result entity (level, message ,namespace ,index, host) but I don't see a reason to put them to report extension (namespace and index is going to be part of query most probably and rest isn't interesting).

Splunk report extension

---

README.md

Closes #408 
The badge is broken for more than 6 months now and noone from the team replies to questions on that issue anymore - so removing it seems like the best way to go.

Removed dependabot badge.

---

jbehave-support-core/docs/Rest-api.md
jbehave-support-core/docs/examples/Rest.md
jbehave-support-core/src/main/java/org/jbehavesupport/core/rest/RestServiceHandler.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Rest.story

One of possible solutions for #463 (JSONPath part)
Open points:
- Is this limited support (user must always start with `$.` if they want to use JSONPath) enough? Or do we want to do it in some other more complicated way (`@json.path` prefix, new step, or something completely different)?
- Does anyone know why IDEA always escapes the dollar sign and if thats a bug or not? (does not seem to be doing this on GitHub though)

Added JSONPath verification support

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md
jbehave-support-core-test/jbehave-support-core-test-oxm/pom.xml
jbehave-support-core-test/pom.xml
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/expression/temporal/NextCalendarDayCommandTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/TestContextImplTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/EqualsVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/GreaterThanOrEqualVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/GreaterThanVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/LowerThanOrEqualVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/LowerThanVerifierTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/internal/verification/NotEqualsVerifierTest.groovy
pom.xml

So far the build fails because of old (and it seems unmaintained) jaxb plugin used in tests to generate java classes from xsd.
We should decide what to do with that - one option is to migrate to maintained and developed: https://github.com/mojohaus/jaxb2-maven-plugin
Or maybe even: http://cxf.apache.org/cxf-xjc-plugin.html

Java upgrade 15->16

---

jbehave-support-core/pom.xml

There was a typo additio**n**nalDependencies (double n) vs additionalDependencies so the config was not used.

Cleanup unused (with typo) javadoc config

---

jbehave-support-core/pom.xml
jbehave-support-core/src/main/java/org/jbehavesupport/core/AbstractSpringStories.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/healthcheck/HealthCheckSteps.java
jbehave-support-core/src/main/java/org/jbehavesupport/core/ssh/SshTemplate.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackChromeT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackFirefoxT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/BrowserStackSafariT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/RequestFactoryTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/context/TestContextIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/filtering/GroovyFilteringTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/healthcheck/HealthCheckStepsTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/report/XmlReportIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/rest/NegativeRestScenariosIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/sql/CheckSqlError.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/sql/DifferentDatabaseResultErrorMessage.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/WebPropertyNegativeIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/web/YamlElementLocatorParserTest.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/RequestResponseAliasIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/SimpleListIT.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/core/ws/ValidateWsResponse.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/SampleStoriesIT.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/Sql.story
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/sample/report/ReportSampleStoriesIT.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/SshGeneratorSteps.java
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestSupport.groovy
jbehave-support-core/src/test/groovy/org/jbehavesupport/test/support/TestSupportBrowserStack.groovy
pom.xml

Migrate to JUnit5 - both in unit tests using jupiter engine and in story files using the custom jbehave engine.
Removed vintage engine (junit4), backwards incompatible change in health check steps since it leaked junit4 API, replaced with soft assertion.
**Snyk is angry due to selenium downgrade - will be fixed later by #769**

Migrate to JUnit5

---

jbehave-support-core/src/main/resources/report-generator/stacktrace.xslt
jbehave-support-core/src/main/resources/report-generator/story.xslt

- fix no steps in report issue
- fix broken link in stacktrace
- add support for parametrized scenarios in report
known parametrized scenario report issues:
- steps with example tables are printed on one line include table (broken formating) - unexpected behaviour of xml report - just don;t put them there, use save as value step to avoid it
- Stacktrace button is broken - wierd XML report failure possition
- no support for story level examples 
- (to have it working use story level examples in LifeCycle bellow narative)
- scenarui name is overriden by example values - jbehave feature probably
know/possible general report issues:
- stories are untitlet in xml report, first scenario name is taken as Story name - wrong
- possible not working links to failed screenshot - need testing
todo:
- …

'Fix' report template for scenarios with examples

---

jbehave-support-core-test/pom.xml

Skip staging plugin for tests (hopefully), since the deploy maven setting seems no longer respected.

Skip staging plugin for tests
